### ISSUE TITLE
Ground Station Arduino xbee code

### ISSUE THREAD

**Issue by ta4anx** [AldaCL/CanSat#2]
Can you please put the code on ground station arduino with xbee module that you specified at readme.md?

**Comment by AldaCL** [comment]
Hi @Kaanduino , code is already placed in /GroundStation folder, it's a Python file named Ultramasterv2.py 

Please check being into master branch; other branches are currently in development.


(I hope it's usefull for you, and I would be very grateful if you could cite my repository as a query source :') )
If some other issue comes up, do not hesitate to consult it! , i'll be  willing to solve it!
Regards!

**Comment by Kaanduino** [comment]
Appreciate it

**Comment by ta4anx** [comment]
Thank you for your answer but I meant  "receiver Arduino Uno" in ground station's code not the ground station's python code.

**Comment by AldaCL** [comment]
Arduino UNO in ground station works like interface USB (PC)- ARDUINO - Xbee (SPI) .
Because I can not get a Xbee USB shield to connect it directly to my PC; if you have one, you can skip Arduino UNO and connect Xbee via USB to your PC and just select the rigth port. 

So, Arduino UNO, only works as ISP brigde to a USB port, which is physically implemented in Arduino UNO board so, it does not need any code to works ; only keep it with a generic  empty .ino  program file, like:
```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```
Excuse me for having forgotten adding a schematic of GS and this especfication. I'll try to add it ASAP. I took it for granted that it was a little obvious. 

Thank you for your questions!
